version: '2.2'
services:

        mariadb:
                container_name: mariadb
                build : src/mariadb/
                volumes: 
                 - /home/qbrillai.42.fr/data/mariadb:/var/lib/mysql
                environment:
                 MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
                 MYSQL_NAME: ${MYSQL_NAME}
                 MYSQL_USER: ${MYSQL_USER}
                 MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                 DOMAIN_NAME: ${DOMAIN_NAME}
                restart: always
                networks :
                 - frontend

        wordpress:
                container_name : wordpress
                build : src/wordpress
                volumes:
                 - /home/qbrillai.42.fr/data/wordpress:/var/www/localhost/wordpress
                depends_on: # Permet d arreter et demarrer les services dans l ordre de dependance.
                 - mariadb
                environment:
                 MYSQL_NAME: ${MYSQL_NAME}
                 MYSQL_USER: ${MYSQL_USER}
                 MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                 DOMAIN_NAME: ${DOMAIN_NAME}
                 WP_ADMIN_NAME: ${WP_ADMIN_NAME}
                 WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
                 WP_USER_NAME: ${WP_USER_NAME}
                 WP_USER_PASSWORD: ${WP_USER_PASSWORD}
                #links:
               #  - mysql
                restart: always
                networks :
                 - frontend

        nginx: #Changer nom de domaine dans VM
                container_name: nginx
                build: src/nginx/
                ports:
                 - "443:443"
                volumes:
                 - /home/qbrillai.42.fr/data/wordpress:/var/www/localhost/wordpress
                restart : always
                networks :
                 - frontend
              
              
networks:
    frontend:
            #        name: frontend
        driver: bridge
