version: '2.2'
services:
  
        nginx:
                container_name: nginx
                build: src/nginx/
                ports:
                #- "80:80"
                 - "443:443"
                volumes:
                 - ./app:/var/www/html
                restart : always
                networks :
                 - frontend

        mysql:
                container_name: mariadb
                build : src/mariadb
                volumes:
                 - /data/mysql:/var/lib/mysql
                environment:
                 MYSQL_ROOT_PASSWORD: mysql_root_pass
                 MYSQL_DATABASE: db_name
                 MYSQL_USER: user_name
                 MYSQL_PASSWORD: user_pass
                 restart: always
                 networks :
                  - frontend
                  - backend
              
              
        networks :
         frontend:
         backend:
