version: '2.2'
services:

        mysql:
                container_name: mariadb
                build : src/mariadb/
                #image : 'mariadb:10.3'
                ports :
                 - "3306:3306"
                volumes: 
                 - ${PWD}/mysql:/var/lib/mysql
                environment:
                 MYSQL_ROOT_PASSWORD: mysql_root_pass
                 MYSQL_DATABASE: db_name
                 MYSQL_USER: user_name
                 MYSQL_PASSWORD: user_pass
                restart: always
                networks :
                 - backend

        wordpress:
                container_name : wordpress
                build : src/wordpress/
                #image: wordpress:php7.3-fpm-alpine
                volumes:
                 - ./app:/var/www/localhost
                depends_on: # Permet d arreter et demarrer les services dans l ordre de dependance.
                 - mysql
                ports :
                 - "9000:9000"
                environment:
                 WORDPRESS_DB_HOST: mysql
                 MYSQL_ROOT_PASSWORD: mysql_root_pass
                 WORDPRESS_DB_NAME: db_name
                 WORDPRESS_DB_USER: user_name
                 WORDPRESS_DB_PASSWORD: user_pass
                 WORDPRESS_TABLE_PREFIX: wp_
                #links:
               #  - mysql
                restart: always
                networks :
                 - backend
                 - frontend

        nginx: #Changer nom de domaine dans VM
                container_name: nginx
                build: src/nginx/
               # image: nginx:alpine
                ports:
                 - "80:80"
                 - "443:443"
                volumes:
                 - ./app:/var/www/html
                # - ./nginx:/etc/nginx/conf.d
                restart : always
                networks :
                 - frontend
                #links:
                # - wordpress
              
              
networks :
 frontend:
 backend:
