version: '2.2'
services:
  
        nginx: #CHanger nom de domaine dans VM
                container_name: nginx
                build: src/nginx/
                ports:
                 - "80:80"
                 - "443:443"
                volumes:
                 - ./app:/var/www/html
                restart : always
                networks :
                 - frontend

        mysql:
                container_name: mariadb
                build : src/mariadb/
                #image : 'mariadb:10.3'
                ports :
                 - "3306:3306"
                volumes: 
                 - ${PWD}/mysql:/var/lib/mysql
                environment:
                 MYSQL_ROOT_PASSWORD: mysql_root_pass
                 MYSQL_DATABASE: db_name
                 MYSQL_USER: user_name
                 MYSQL_PASSWORD: user_pass
                restart: always
                networks :
                 - backend
        
      #  wordpress:
        #        container_name : wordpress
         #       build : src/wordpress
         #       ports :
         #        - "9000:9000"

              
              
networks :
 frontend:
 backend:
