version: '2.2'
services:
  
        nginx:
                container_name: nginx
                build: src/nginx/
                ports:
                #- "80:80"
                 - "443:443"
                volumes:
                 - ./app:/var/www/html
                restart : always
                networks :
                 - frontend

networks :
        frontend:
        backend:
